Repository NVIDIA/GenerativeAIExamples, pull requests merged in 2024-04, with the labels that each got.

#98 Fix links in experimental ORAN readme
  experimental/oran-chatbot-multimodal/README.md
Labels: bug

#103 models: Add notebook for finetuning Google CodeGemma model
  models/Codegemma/README.md
  models/Codegemma/lora.ipynb
  models/README.md
Labels: enhancement

#109 Add inventory of Gen AI model examples to the README
  README.md
Labels: documentation
