Repository NVIDIA/GenerativeAIExamples, pull requests merged in 2024-07, with the labels that each got.

#143 Add a what's new section in README file
  README.md
Labels: documentation

#144 Add RAG knowledge graph based experimental example
  experimental/README.md
  experimental/knowledge_graph_rag/README.md
  experimental/knowledge_graph_rag/app.py
  experimental/knowledge_graph_rag/pages/chat.py
  experimental/knowledge_graph_rag/pages/evaluation.py
  experimental/knowledge_graph_rag/pages/visualization.py
  experimental/knowledge_graph_rag/requirements.txt
  experimental/knowledge_graph_rag/utils/download_papers.py
  experimental/knowledge_graph_rag/utils/lc_graph.py
  experimental/knowledge_graph_rag/utils/preprocessor.py
  experimental/knowledge_graph_rag/vectorstore/search.py
  experimental/knowledge_graph_rag/viz.png
Labels: enhancement

#146 Fix pre-commit config file
  .pre-commit-config.yaml
Labels: bug

#147 Migrate what's new section to top of readme
  README.md
Labels: documentation
