Repository NVIDIA/GenerativeAIExamples, pull requests merged in 2024-09, with the labels that each got.

#184 Update docker compose plugin version in prerequisites
  docs/common-prerequisites.md
Labels: bug

#179 Update doc to delete ingested file using UI
  docs/using-sample-web-application.md
Labels: documentation, enhancement

#187 Add support NeMo Retriever Text Reranking NIM in O-RAN chatbot
  community/oran-chatbot-multimodal/Multimodal_Assistant.py
  community/oran-chatbot-multimodal/config.yaml
Labels: enhancement

#189 Update Gradio version to 4.43.0
  RAG/src/rag_playground/requirements.txt
Labels: bug

#193 Restructure and rewrite README.md
  README.md
Labels: documentation

#194 Update requirements.txt
  community/multimodal-rag/requirements.txt
Labels: bug

#186 added langChain RAG notebook that uses NIM + embedding model from HF + FAISS VDB
  community/llm_video_series/data/.DS_Store
  community/llm_video_series/data/imgs/offline.png
  community/llm_video_series/data/imgs/online.png
  community/llm_video_series/video_1_llamaindex_basic_RAG.ipynb
  community/llm_video_series/video_2_multimodal-rag/README.md
  community/llm_video_series/video_2_multimodal-rag/app.py
  community/llm_video_series/video_2_multimodal-rag/document_processors.py
  community/llm_video_series/video_2_multimodal-rag/requirements.txt
  community/llm_video_series/video_2_multimodal-rag/utils.py
  community/llm_video_series/video_3_langchain_copilot_with_NIM_HF_FAISS_deployed_locally.ipynb
  community/multimodal-rag/vectorstore/.gitkeep
  community/multimodal-rag/vectorstore/image_references/.gitkeep
  community/multimodal-rag/vectorstore/ppt_references/.gitkeep
  community/multimodal-rag/vectorstore/table_references/.gitkeep
Labels: enhancement

#200 Add NeMo Retriever SDG
  nemo/retriever-synthetic-data-generation/README.md
  nemo/retriever-synthetic-data-generation/data/nq_test.jsonl
  nemo/retriever-synthetic-data-generation/data/sample_data_rawdoc.jsonl
  nemo/retriever-synthetic-data-generation/data/sample_data_squad.json
  nemo/retriever-synthetic-data-generation/figures/api_key.png
  nemo/retriever-synthetic-data-generation/figures/sample_output.png
  nemo/retriever-synthetic-data-generation/figures/sdg_pipeline.png
  nemo/retriever-synthetic-data-generation/nemo_retriever_sdg/__init__.py
  nemo/retriever-synthetic-data-generation/nemo_retriever_sdg/analyzer.py
  nemo/retriever-synthetic-data-generation/nemo_retriever_sdg/calculator.py
  nemo/retriever-synthetic-data-generation/nemo_retriever_sdg/dataset.py
  nemo/retriever-synthetic-data-generation/nemo_retriever_sdg/evaluator.py
  nemo/retriever-synthetic-data-generation/nemo_retriever_sdg/filter.py
  nemo/retriever-synthetic-data-generation/nemo_retriever_sdg/processor.py
  nemo/retriever-synthetic-data-generation/nemo_retriever_sdg/qa_generator.py
  nemo/retriever-synthetic-data-generation/nemo_retriever_sdg/rewriter.py
  nemo/retriever-synthetic-data-generation/nemo_retriever_sdg/verifier.py
  nemo/retriever-synthetic-data-generation/notebooks/quickstart.ipynb
  nemo/retriever-synthetic-data-generation/outputs/.gitkeep
  nemo/retriever-synthetic-data-generation/requirements.txt
  nemo/retriever-synthetic-data-generation/scripts/conf/config-fiqa.yaml
  nemo/retriever-synthetic-data-generation/scripts/conf/config-nq.yaml
  nemo/retriever-synthetic-data-generation/scripts/conf/config.yaml
  nemo/retriever-synthetic-data-generation/scripts/run_pipeline.py
Labels: enhancement

#204 fix: fix error when loading the tool
  community/llm-prompt-design-helper/Dockerfile
  community/llm-prompt-design-helper/requirements.txt
Labels: bug
