Repository NVIDIA/GenerativeAIExamples, pull requests merged in 2024-08, with the labels that each got.

#157 Add new tool : llm prompt design helper
  experimental/README.md
  experimental/llm-prompt-design-helper/.gitattributes
  experimental/llm-prompt-design-helper/Dockerfile
  experimental/llm-prompt-design-helper/README.md
  experimental/llm-prompt-design-helper/api_request_backends/api_request.py
  experimental/llm-prompt-design-helper/api_request_backends/chatnv_client.py
  experimental/llm-prompt-design-helper/api_request_backends/openai_client.py
  experimental/llm-prompt-design-helper/build_image.sh
  experimental/llm-prompt-design-helper/chat_ui.py
  experimental/llm-prompt-design-helper/chat_ui_utils.py
  experimental/llm-prompt-design-helper/config.yaml
  experimental/llm-prompt-design-helper/data/bot.webp
  experimental/llm-prompt-design-helper/data/llm-prompt-designer-demo.gif
  experimental/llm-prompt-design-helper/data/local-database-settings.jpeg
  experimental/llm-prompt-design-helper/data/self-host-database-settings.jpeg
  experimental/llm-prompt-design-helper/data/simple_ui.jpeg
  experimental/llm-prompt-design-helper/data/simple_ui_db.jpeg
  experimental/llm-prompt-design-helper/data/user.webp
  experimental/llm-prompt-design-helper/requirements.txt
  experimental/llm-prompt-design-helper/run_container.sh
  experimental/llm-prompt-design-helper/test.py
  experimental/llm-prompt-design-helper/vector_store/faiss_vector_store.py
Labels: enhancement

#167 [RAG][Notebooks]: Refactor Langchain agent notebook to use llama-3.1
  RAG/notebooks/langchain/Agent_use_tools_leveraging_NVIDIA_AI_endpoints.ipynb
Labels: enhancement

#169 Update README.md
  README.md
Labels: bug

#170 update whats new
  README.md
Labels: documentation
